README.md
leads_gui/config.py
leads_gui/prototype.py
leads_vec/cli.py

PROPOSED IN #46 
Raspberry Pi compatibility is still pending verification.

Migrate the GUI Platform to CutomTkinter

---

leads/comm/prototype.py

socket.gaierror: [Errno 8] nodename nor servname provided, or not known

---

leads/data_persistence.py

Replace Regular Copy with List Copy in Data Persistence

---

leads_audio/__init__.py

Include `pysdl2-dll` in the Optional Dependencies

---

leads_vec/__main__.py
leads_vec/_bootloader/systemd.py

ImportError: cannot import name 'getuid' from 'os'. Did you mean: 'getpid'?

---

leads_vec/_bootloader/leads_vec.service.sh

OSError: [Errno 6] No such device or address

---

README.md
leads_audio/prototype.py
leads_vec/_bootloader/leads_vec.service.sh
leads_vec/_bootloader/systemd.py
scripts/frp-config.sh
scripts/frp-install.sh
scripts/obs-install.sh
scripts/obs-run.sh
scripts/python-install.sh
scripts/setup.sh

No Display Environment when the Systemd Service Initializes

---

leads_vec/_bootloader/leads_vec.service.sh
leads_vec/_bootloader/systemd.py
scripts/frp-config.sh
scripts/frp-install.sh
scripts/obs-install.sh
scripts/obs-run.sh
scripts/python-install.sh
scripts/setup.sh

Systemd Service Permission Denied

---

leads_gui/performance_checker.py
leads_gui/prototype.py
leads_vec/devices.py
leads_vec/devices_jarvis.py
leads_video/camera.py
leads_video/utils.py

The Program Freezes after a Certain While

---

leads_vec/cli.py
leads_vec_rc/cli.py

Add More Control Features to the Remote Analyst

---

leads_vec/cli.py
leads_vec/devices.py

Integrate the Direction Indicator Animation into the Device

---

leads/sft.py
leads_vec/cli.py
leads_vec/devices.py

Detect the Absence of Devices during the Initialization of the Main Controller and Notify the SFT

---

leads_vec_rc/cli.py
leads_vec_rc/jarvis.py

Put the Jarvis Processor of the Remote Analyst in a Separate Thread

---

leads_gui/photo.py
leads_vec/cli.py

Add a Photo Widget that Directly Accepts PIL Images

---

leads_video/camera.py

Provide a Separate Interface in Cameras that Outputs PIL Images

---

leads/comm/client/__init__.py
leads/comm/client/client.py
leads/comm/server/__init__.py
leads/comm/server/server.py

Support Customizing the Separators for Servers and Clients

---

leads/comm/prototype.py

Entities are not Properly Closed

---

leads_vec_rc/cli.py

Remove AI Features from the Remote Analyst

---

README.md
leads/config/template.py
leads_gui/config.py

Move Config `data_dir` Out of the Template

---

leads/data.py
leads_vec/cli.py
leads_vec/devices.py
leads_video/__init__.py
leads_video/base64.py
leads_video/camera.py
leads_video/utils.py

Record the Delays Introduced by Base64 Encoding in `VisualDataContainer`

---

leads/data_persistence/core.py
leads/types.py
leads_vec_rc/cli.py

Support Saving Visual Data

---

leads_can/__init__.py
leads_can/obd.py
leads_can/prototype.py

Support CAN Bus

---

leads/sft.py
leads_gui/__init__.py
leads_gui/prototype.py
leads_vec/cli.py
leads_vec/devices.py

Premature Call to Tkinter

---

leads_gui/prototype.py

Secondary Screens Do not Correctly Locate on Windows

---

arduino/leads_vec_power/Pedal.cpp
arduino/leads_vec_power/Pedal.h
arduino/leads_vec_power/leads_vec_power.ino
leads_arduino/__init__.py
leads_arduino/pedal.py

Support Pedals as Built-in Devices

---

leads/comm/prototype.py
leads/data_persistence/analyzer/inference.py
leads/data_persistence/analyzer/processor.py
leads/ltm.py
leads_arduino/wheel_speed_sensor.py
leads_comm_serial/connection.py
leads_gui/performance_checker.py
leads_video/utils.py

Use Scientific Notations for Small Float Numbers
