leads/__init__.py
leads/context.py
leads/leads.py
leads/plugin/__init__.py
leads/plugin/abs.py
leads/plugin/atbs.py
leads/plugin/dtcs.py
leads/plugin/ebi.py
leads/plugin/plugin.py
leads/types.py
leads_vec/cli.py

Subsystems as Plugins

---

leads/__init__.py
leads/comm/prototype.py
leads/comm/server/server.py
leads/dt/device.py
leads/os.py

Device Threads are not Killed when the GUI Thread has Exited

---

README.md
leads/config/template.py
leads/data.py
leads/data_persistence.py
leads/types.py
leads_emulation/__init__.py
leads_emulation/replay.py
leads_vec/__main__.py
leads_vec/controllers.py
leads_vec_rc/cli.py
setup.py

Support Replaying from Recorded Data

---

leads/config/template.py
leads_vec/cli.py

Support Specifying `num_laps_timed` through Config

---

leads/comm/prototype.py

socket.herror: [Errno 1] Unknown host

---

leads_arduino/wheel_speed_sensor.py
leads_gui/performance_checker.py
leads_gui/prototype.py
leads_vec/cli.py

Introduce Polynomial Regression to the Performance Checker

---

leads_vec/__main__.py
leads_vec/_bootloader/frp.py

Improve `leads_vec` Debugging Information

---

design/obs-config.json

As discussed in the meeting, we uploaded our OBS Studio configuation for the automation of production deployment.

Add Configuation for OBS Studio

---

scripts/obs-run.sh

OBS Studio Fails to Initialize

---

design/obs-config.json

Fix the Invalid OBS Studio Layout Configuation

---

scripts/setup.sh

`setup.sh` Exits Unexpectedly

---

leads_vec/_bootloader/systemd.py

FileExistsError: [Errno 17] File exists: '/usr/local/leads'

---

README.md
leads_vec/__main__.py
leads_vec/_bootloader/leads-vec.service.sh
leads_vec/_bootloader/leads_vec.service.sh
leads_vec/_bootloader/systemd.py
leads_vec_rc/cli.py
scripts/frp-config.sh
scripts/frp-install.sh
setup.py

Autostart Works Partially on Raspberry Pi

---

leads_vec/_bootloader/systemd.py

Failed to enable unit: Unit file /home/projectneura/.config/systemd/user/default.target.wants/leads-vec.service does not exist

---

README.md
leads_vec/_bootloader/leads-vec.service.sh
scripts/frp-config.sh
scripts/frp-install.sh
scripts/obs-install.sh
scripts/obs-run.sh
scripts/python-install.sh
scripts/setup.sh
scripts/uninstall.sh

Add a Script for Uninstalling

---

leads_vec/__init__.py
leads_vec/__main__.py
leads_vec/cli.py
leads_vec/replay.py
leads_vec/run.py

Add Private Credentials to a Private Repository

---

README.md
leads_vec/__main__.py
leads_vec/run.py

Support Custom Main Functions

---

leads_vec_rc/cli.py

Error Data Output File

---

leads/context.py
leads/event.py
leads/leads.py

Incorrect Hazard Light Logic

---

leads/__init__.py
leads/dt/registry.py
leads/os.py
leads_audio/prototype.py
leads_vec/run.py
leads_vec_rc/cli.py

Devices are not Properly Closed

---

leads_vec/_bootloader/systemd.py

Serial Port Permission Denied

---

scripts/setup.sh

Permission Denied when Executing `setup.sh`

---

leads_vec/_bootloader/systemd.py

Group "dialoutusername" does not Exist

---

leads_arduino/wheel_speed_sensor.py
leads_vec/devices.py

Support Multiple Magnets on the Wheel

---

leads_vec/devices.py

Support GPS Only Mode

---

leads_raspberry_pi/led.py
leads_raspberry_pi/led_group.py
leads_vec/cli.py
leads_vec/run.py

Use `match` Instead of `if` Trees

---

leads_vec/cli.py

TypeError: called match pattern must be a class

---

leads/data_persistence/core.py
leads_vec_rc/cli.py

Include Throttle and Brake Data in the Default Header

---

leads/callback.py

Improve the Efficiency of Calling the Super Method in `CallbackChain`

---

leads/data.py
leads_video/__init__.py
leads_video/camera.py
leads_video/utils.py

Include Front View in the Data Container

---

leads_emulation/__init__.py

Support Throttle and Brake Emulation

---

leads_vec/__main__.py

Simplify the Path of Package `leads_vec` with a Keyword

---

leads_vec/__main__.py
leads_vec/run.py

AttributeError: 'NoneType' object has no attribute 'replace'

---

leads/context.py

Improve Direction Indicator Logic

---

leads/config/template.py
leads/types.py
leads_vec/devices_jarvis.py

Restrict the Types of Attributes in `Config`

---

leads/config/registry.py

Use `Callable[...]` Instead of `type[...]` for Type Hints

---

leads_gui/__init__.py
leads_gui/accelerometer.py
leads_gui/photo.py
leads_gui/prototype.py
leads_gui/proxy.py
leads_vec/cli.py
leads_vec/devices.py
leads_vec/devices_jarvis.py
leads_video/camera.py
leads_video/utils.py

Add a Video Player Widget

---

leads_gui/photo.py

The Video Player is Laggy and Often Fails

---

leads/context.py
leads_vec/cli.py
leads_vec_rc/cli.py

Display the Rear View Instead of the Front View

---

leads_vec/cli.py

Hide the Video Player if No Rear-view Camera is Found

---

leads_vec/cli.py

Remove the Hotkey to Quit the Program

---

leads_video/camera.py
leads_video/utils.py

Accelerate Base64 Encoding

---

leads_vec_rc/cli.py
leads_vec_rc/jarvis.py

Introduce Jarvis to the Remote Analyst

---

scripts/python-install.sh

`python-install.sh` Requires User Interactions to Proceed

---

leads_gui/photo.py

`None` Objects are Passed to the Constructor of `VariableControlled`

---

leads_gui/prototype.py

`RuntimeData` Has an Unused Attribute `lap_time`

---

leads_video/camera.py

Provide a Separate Interface in Cameras that Outputs Numpy Arrays

---

leads_gui/config.py
leads_gui/photo.py
leads_gui/prototype.py
leads_vec/cli.py
leads_video/camera.py
leads_video/utils.py

Add a Dedicated Streaming Server

---

leads_vec_rc/__main__.py

The Remote Controller Tries to Initialize before the Config has been Registered

---

leads_gui/prototype.py

Support `None` Values as Placeholders in Layout

---

leads_vec/cli.py

Add a Status Label for the Comm Stream Server

---

leads/comm/prototype.py
leads_comm_serial/connection.py

Connections are not Disconnected before an Entity is Closed

---

leads/data_persistence/analyzer/__init__.py
leads/data_persistence/analyzer/inference.py
leads/data_persistence/analyzer/preprocess.py
leads/data_persistence/analyzer/processor.py
leads/data_persistence/core.py

Support Realigning Data Frames and Video Frames

---

leads/dt/device.py

Supports Full-duplex Serial Communication within a Single Arduino Thread

---

leads_gui/prototype.py
leads_gui/speedometer.py
leads_vec/cli.py

The Main Window does not Respond to Clicking after the Secondary Window is Focused Once

---

leads_vec/_bootloader/leads-vec.service.sh

Use `leads-vec` Everywhere Instead of `python -m leads_vec`

---

leads_vec/cli.py

The Secondary Screen does not Render

---

leads_gui/performance_checker.py

RuntimeWarning: Mean of empty slice

---

leads_gui/photo.py
leads_video/base64.py
leads_video/types.py
leads_video/utils.py

Support Extracting the Visual Data in a CSV File to MP4

---

README.md
leads_emulation/replay.py
leads_vec/config.py
leads_vec/replay.py
leads_video/utils.py
scripts/setup.sh

Cameras do not Exist when Replaying

---

leads_vec/devices.py

Cannot Import "_" from `devices.py`

---

leads_vec/cli.py

Debug Window Fails to Close on Windows Platform

---

leads_vec/devices.py

The Main Controller does not Reset as Expected

---

leads_video/base64.py
leads_video/camera.py

Use OpenCV Standard [height, width, channel]

---

leads_vec/run.py

Add All-in-one Installation Scripts for Specific Vehicles

---

leads/data.py
leads/dt/predefined_tags.py
leads/leads.py
leads/plugin/abs.py
leads/plugin/atbs.py
leads/plugin/dtcs.py
leads/plugin/ebi.py
leads/plugin/plugin.py
leads/sft.py
leads_vec/devices.py

Complete ECS Plugins

---

README.md
leads/comm/prototype.py
leads/data_persistence/analyzer/inference.py
leads_arduino/arduino_proto.py
leads_comm_serial/__init__.py
leads_comm_serial/connection.py
leads_comm_serial/identity.py
leads_gpio/gps_receiver.py
leads_vec/cli.py
leads_vec/devices.py
leads_video/utils.py

Support Serial Port Identification

---

leads_arduino/arduino_proto.py
leads_arduino/voltage_sensor.py
leads_arduino/wheel_speed_sensor.py

Filter Arduino Update Broadcast

---

leads/comm/client/client.py
leads/comm/prototype.py
leads/comm/server/server.py
leads/event.py
leads/leads.py
leads/sft.py
leads_arduino/arduino_proto.py
leads_comm_serial/connection.py
leads_comm_serial/identity.py
leads_gpio/gps_receiver.py
leads_vec/cli.py

Trying the Wrong Port Creates Conflicts with Other Instances

---

leads/leads.py

Suspension Events do not Stop Plugins from Running

---

leads_gui/prototype.py
leads_vec/cli.py

Windows are not Stated as Inactive after Death

---

leads/data.py
leads/data_persistence/core.py
leads/types.py

Add Steering Position Data

---

leads_comm_serial/connection.py
leads_comm_serial/identity.py

Serial Port Recognization is Obstructed by Non-responding Targets

---

leads_comm_serial/connection.py
leads_comm_serial/identity.py

Permission Denied due to Contention

---

leads/data.py
leads/data_persistence/core.py
leads/types.py

Add Proximity Data in the Data Container

---

leads_comm_serial/identity.py
leads_gpio/gps_receiver.py

Unreasonable Assumption of Separator

---

leads/dt/controller.py
leads/dt/device.py
leads/dt/registry.py

Disallow Changing Devices' Tags after Registration

---

leads_vec/cli.py

Use Frequency Generators to Update Non-context-related Content

---

leads_gui/performance_checker.py
leads_gui/prototype.py
leads_vec/cli.py

Make Time a Factor of the Performance Checker

---

arduino/leads_vec_wsc/Accelerometer.cpp
arduino/leads_vec_wsc/Accelerometer.h
arduino/leads_vec_wsc/leads_vec_wsc.ino
leads/data.py
leads/data_persistence/core.py
leads/types.py
leads_arduino/__init__.py
leads_arduino/accelerometer.py
leads_can/prototype.py
leads_vec/devices.py

Implement the G Force Recording System

---

README.md
leads_vec_dp/run.py

Typo: "mileage" as "milage"

---

leads_gui/prototype.py
leads_vec/cli.py
leads_vec/devices_visual.py
leads_video/camera.py

Use OpenCV instead of Pillow for Base64 Encoding

---

arduino/leads_vec_wsc/Accelerometer.cpp
leads_arduino/accelerometer.py
leads_vec/devices.py

Remove Gravity from Acceleration

---

leads/sft.py

KeyError('gps') when the GPS Receiver Recovers

---

README.md

Replace the Term "Raspberry Pi" with "SBC"

---

leads_vec/devices_visual.py

Support Specifying Camera Encoding Quality in the Config

---

leads_vec/__entry__.py
leads_vec/benchmark.py

Add a Benchmark Program

---

README.md
leads_vec/benchmark.py

Support Custom Camera Port Used in the Benchmark

---

leads_vec/benchmark.py

The Delays should not Possitively Contribute to the Score

---

leads_vec/cli.py

Catch Failed Attempts on Playing Sounds

---

leads/data_persistence/_computational/__init__.py
leads/data_persistence/core.py
leads_vec_rc/cli.py

TypeError: unhashable type: 'numpy.ndarray'

---

leads_vec_rc/cli.py

Use Three.js to Display the Vehicle Status on the Remote Analyst Website

---

leads/context.py

Simplify the Calculation of Speed Trend

---

leads_vec_rc/cli.py

Default Data Container when the Remote Analyst Initializes causes Frontend Error

---

leads/data_persistence/analyzer/processor.py

Visual Data is not Optional in Data Processor

---

leads_arduino/accelerometer.py

Linear Acceleration should not be Linear Again

---

leads_vec_rc/cli.py

The Lateral CFC Offsets are Inversed

---

leads_comm_serial/sobd/__init__.py
leads_comm_serial/sobd/sobd.py
leads_vec/devices.py

`SOBD` is not Exported

---

leads/data_persistence/analyzer/processor.py
leads_gui/__init__.py
leads_gui/performance_checker.py
leads_gui/prototype.py
leads_gui/speedometer.py
leads_vec/benchmark.py
leads_vec/cli.py

Support Dialog Boxes

---

leads_vec/cli.py
leads_vec/devices.py

TypeError: Button.__init__() missing 1 required positional argument: 'pin'

---

leads/context.py
leads_vec/cli.py

Hazard Lights Flashing Error when One of the Turn Signals is On

---

leads_vec_rc/cli.py

Unmatched Config Entries in LEADS VeC Remote Analyst

---

arduino/leads_vec_power/Pedal.h
arduino/leads_vec_power/leads_vec_power.ino

Support Pedals as Built-in Devices

---

README.md
leads_vec/__init__.py
leads_vec/cli.py
leads_vec/devices.py
leads_vec/utils.py

An Easier Way to Insert Custom ESC Plugins

---

README.md
leads/data_persistence/analyzer/inference.py
leads_vec_dp/run.py

Support Quick Entry Clearing in LEADS VeC Data Processor

---

leads/data_persistence/analyzer/inference.py
leads/dt/registry.py
leads_gui/prototype.py

Encourage More Use of `enumerate()`
